"""
Snowflake Feature Store Bridge
===============================

Python backend for snowflakeR::R/features.R.

This module wraps the snowflake.ml.feature_store Python API, providing
functions callable from R via reticulate. Each function receives a Snowpark
session object (from the sfr_connection) and performs Feature Store operations.

Key design decisions:
  - All pandas DataFrames returned to R are converted via JSON round-trip
    (pandas_to_r_dict) to avoid NumPy 1.x/2.x ABI issues with reticulate.
  - The FeatureStore object is instantiated per-call or cached in the R-side
    connection object to avoid stale references.
  - FeatureView source data is passed as SQL strings from R (generated by
    dbplyr or written manually), then wrapped in session.sql().
"""

from typing import Dict, List, Optional, Any


# =============================================================================
# Internal helpers
# =============================================================================


def _to_json_tempfile(pdf):
    """Write a pandas DataFrame to a temp JSON file and return the path.

    Avoids the ``basic_string::substr`` C++ crash in reticulate/rpy2 that
    occurs when large dicts cross the Python <-> R bridge in Workspace
    Notebooks.  The R side reads and parses the file with jsonlite.
    """
    import json
    import tempfile

    d = _pandas_to_r_dict(pdf)
    tmp = tempfile.NamedTemporaryFile(
        mode="w", suffix=".json", delete=False, prefix="sfr_features_"
    )
    json.dump(d, tmp)
    tmp.close()
    return tmp.name


def _pandas_to_r_dict(pdf):
    """Convert a pandas DataFrame to a column-oriented dict with native Python
    types via Series.tolist().  This avoids NumPy ABI issues with reticulate
    and is more efficient than the previous JSON round-trip approach.

    Datetime columns are converted to ISO-format strings to avoid ugly
    POSIX timestamp objects in R output.

    NOTE: For very large datasets, an Apache Arrow IPC transfer (pyarrow on
    the Python side, arrow R package on the R side) would be significantly
    faster.  See TODO.md for the roadmap item.
    """
    import datetime

    _NA = "NA_SENTINEL_"
    clean_cols = [c.strip('"') for c in pdf.columns]
    pdf.columns = clean_cols
    cols = list(clean_cols)
    nrows = len(pdf)

    if nrows == 0:
        return {"columns": cols, "data": {c: [] for c in cols}, "nrows": 0}

    data = {}
    for col in cols:
        na_mask = pdf[col].isna()
        vals = pdf[col].tolist()

        # Convert datetime objects to ISO strings
        if vals and isinstance(vals[0], (datetime.datetime, datetime.date)):
            vals = [v.isoformat() if isinstance(v, (datetime.datetime, datetime.date)) else v for v in vals]

        if na_mask.any():
            data[col] = [_NA if is_na else (_NA if v is None else v)
                         for v, is_na in zip(vals, na_mask)]
        else:
            data[col] = [_NA if v is None else v for v in vals]

    return {"columns": cols, "data": data, "nrows": nrows}


_fs_cache: Dict[tuple, Any] = {}


def _get_feature_store(
    session,
    database: str,
    schema: str,
    default_warehouse: str,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
):
    """
    Get or create a FeatureStore instance, cached by (db, schema, warehouse, mode).

    Args:
        session: Active Snowpark Session.
        database: Database containing the Feature Store schema.
        schema: Schema name for the Feature Store.
        default_warehouse: Default warehouse for compute.
        creation_mode: "CREATE_IF_NOT_EXIST" or "FAIL_IF_NOT_EXIST".

    Returns:
        FeatureStore instance.
    """
    cache_key = (database, schema, default_warehouse, creation_mode)
    if cache_key in _fs_cache:
        return _fs_cache[cache_key]

    from snowflake.ml.feature_store import FeatureStore, CreationMode

    mode_map = {
        "CREATE_IF_NOT_EXIST": CreationMode.CREATE_IF_NOT_EXIST,
        "FAIL_IF_NOT_EXIST": CreationMode.FAIL_IF_NOT_EXIST,
    }
    mode = mode_map.get(creation_mode, CreationMode.FAIL_IF_NOT_EXIST)

    fs = FeatureStore(
        session=session,
        database=database,
        name=schema,
        default_warehouse=default_warehouse,
        creation_mode=mode,
    )
    _fs_cache[cache_key] = fs
    return fs


def _make_entity(name: str, join_keys: List[str], desc: Optional[str] = None):
    """Create a local (draft) Entity object."""
    from snowflake.ml.feature_store import Entity
    return Entity(name=name, join_keys=join_keys, desc=desc or "")


def _make_feature_view(
    session,
    name: str,
    entities: list,
    sql: str,
    refresh_freq: Optional[str] = None,
    warehouse: Optional[str] = None,
    timestamp_col: Optional[str] = None,
    desc: Optional[str] = None,
):
    """
    Create a local (draft) FeatureView object.

    Args:
        session: Active Snowpark Session.
        name: FeatureView name.
        entities: List of Entity objects.
        sql: SQL query defining the feature transformation.
        refresh_freq: Refresh frequency string (e.g., "1 hour") or None.
        warehouse: Override warehouse for this FeatureView.
        timestamp_col: Timestamp column name for time-series features.
        desc: Description.

    Returns:
        A draft FeatureView object.
    """
    from snowflake.ml.feature_store import FeatureView

    feature_df = session.sql(sql)

    fv = FeatureView(
        name=name,
        entities=entities,
        feature_df=feature_df,
        refresh_freq=refresh_freq,
        timestamp_col=timestamp_col,
        desc=desc or "",
        warehouse=warehouse,
    )

    return fv


# =============================================================================
# Entity operations
# =============================================================================

def register_entity(
    session,
    name: str,
    join_keys: List[str],
    desc: Optional[str] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "CREATE_IF_NOT_EXIST",
) -> Dict[str, Any]:
    """
    Create and register an entity in the Feature Store.

    Args:
        session: Active Snowpark Session.
        name: Entity name.
        join_keys: List of join key column names.
        desc: Entity description.
        database: Feature Store database.
        schema: Feature Store schema.
        warehouse: Default warehouse.
        creation_mode: "CREATE_IF_NOT_EXIST" or "FAIL_IF_NOT_EXIST".

    Returns:
        Dict with entity info (name, join_keys, desc).
    """
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    entity = _make_entity(name, join_keys, desc)
    registered = fs.register_entity(entity)

    return {
        "name": registered.name if hasattr(registered, 'name') else name,
        "join_keys": join_keys,
        "desc": desc or "",
    }


def get_entity(
    session,
    name: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Dict[str, Any]:
    """Retrieve a registered entity by name."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    entity = fs.get_entity(name)

    return {
        "name": entity.name,
        "join_keys": list(entity.join_keys),
        "desc": getattr(entity, 'desc', ''),
    }


def list_entities(
    session,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Any:
    """List all entities in the Feature Store. Returns a pandas DataFrame."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    return _pandas_to_r_dict(fs.list_entities().to_pandas())


def delete_entity(
    session,
    name: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> None:
    """Delete an entity by name."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fs.delete_entity(name)


# =============================================================================
# Feature View operations
# =============================================================================

def register_feature_view(
    session,
    name: str,
    version: str,
    sql: str,
    entity_names: List[str],
    entity_join_keys: Optional[List[List[str]]] = None,
    refresh_freq: Optional[str] = None,
    warehouse: Optional[str] = None,
    timestamp_col: Optional[str] = None,
    desc: Optional[str] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    overwrite: bool = False,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Dict[str, Any]:
    """
    Register a Feature View in the Snowflake Feature Store.

    Entities must already be registered. This function:
    1. Connects to the Feature Store.
    2. Retrieves the named entities.
    3. Creates a draft FeatureView from the SQL + entities.
    4. Registers (materialises) the FeatureView.

    Args:
        session: Active Snowpark Session.
        name: FeatureView name.
        version: Version string (e.g., "v1").
        sql: SQL defining the feature transformation.
        entity_names: List of registered entity names.
        entity_join_keys: Not used when entities are pre-registered.
        refresh_freq: Refresh frequency (e.g., "1 hour", "0 30 * * *").
        warehouse: Warehouse override.
        timestamp_col: Timestamp column for time-series features.
        desc: Description.
        database: Feature Store database.
        schema: Feature Store schema.
        overwrite: If True, overwrite existing version.
        creation_mode: FeatureStore creation mode.

    Returns:
        Dict with registered FeatureView info.
    """
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)

    # Retrieve registered entities
    entities = [fs.get_entity(en) for en in entity_names]

    # Create draft FeatureView
    fv = _make_feature_view(
        session=session,
        name=name,
        entities=entities,
        sql=sql,
        refresh_freq=refresh_freq,
        warehouse=wh,
        timestamp_col=timestamp_col,
        desc=desc,
    )

    # Register (materialise)
    registered_fv = fs.register_feature_view(
        feature_view=fv,
        version=version,
        overwrite=overwrite,
    )

    return {
        "name": registered_fv.name,
        "version": registered_fv.version,
        "status": str(registered_fv.status),
        "desc": getattr(registered_fv, 'desc', desc or ''),
    }


def get_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Dict[str, Any]:
    """Retrieve a registered FeatureView by name and version."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fv = fs.get_feature_view(name, version)

    return {
        "name": fv.name,
        "version": fv.version,
        "status": str(fv.status),
        "desc": getattr(fv, 'desc', ''),
        "timestamp_col": getattr(fv, 'timestamp_col', None),
        "_py_fv": fv,  # Keep Python object for downstream use
    }


def list_feature_views(
    session,
    entity_name: Optional[str] = None,
    feature_view_name: Optional[str] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Any:
    """List Feature Views. Returns a pandas DataFrame."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    kwargs = {}
    if entity_name:
        kwargs["entity_name"] = entity_name
    if feature_view_name:
        kwargs["feature_view_name"] = feature_view_name

    return _pandas_to_r_dict(fs.list_feature_views(**kwargs).to_pandas())


def delete_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> None:
    """Delete a registered FeatureView."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fs.delete_feature_view(name, version)


def refresh_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> None:
    """Manually refresh a FeatureView."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fs.refresh_feature_view(name, version)


def read_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Any:
    """Read data from a registered FeatureView. Returns pandas DataFrame."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    return _pandas_to_r_dict(fs.read_feature_view(name, version).to_pandas())


def suspend_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> None:
    """Suspend a FeatureView's automatic refresh."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fs.suspend_feature_view(name, version)


def resume_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> None:
    """Resume a suspended FeatureView's automatic refresh."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fs.resume_feature_view(name, version)


# =============================================================================
# Training data generation
# =============================================================================

def generate_training_set(
    session,
    spine_sql: str,
    feature_view_refs: List[Dict[str, str]],
    spine_timestamp_col: Optional[str] = None,
    spine_label_cols: Optional[List[str]] = None,
    save_as: Optional[str] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Any:
    """
    Generate a training set by joining spine data with Feature Views.

    Args:
        session: Active Snowpark Session.
        spine_sql: SQL query or table name for the spine (label) data.
        feature_view_refs: List of dicts with "name" and "version" keys.
        spine_timestamp_col: Timestamp column in spine for PIT joins.
        spine_label_cols: Label column names in spine.
        save_as: Optional table name to materialise results.
        database: Feature Store database.
        schema: Feature Store schema.
        warehouse: Default warehouse.

    Returns:
        pandas DataFrame with the training data.
    """
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)

    # Build spine DataFrame
    spine_df = session.sql(spine_sql)

    # Retrieve registered FeatureViews
    fvs = []
    for ref in feature_view_refs:
        fv = fs.get_feature_view(ref["name"], ref["version"])
        fvs.append(fv)

    kwargs = {}
    if spine_timestamp_col:
        kwargs["spine_timestamp_col"] = spine_timestamp_col
    if spine_label_cols:
        kwargs["spine_label_cols"] = spine_label_cols
    if save_as:
        kwargs["save_as"] = save_as

    result_df = fs.generate_training_set(
        spine_df=spine_df,
        features=fvs,
        **kwargs,
    )

    return _to_json_tempfile(result_df.to_pandas())


# Module-level cache for Dataset objects so sfr_log_model can retrieve
# a Snowpark DataFrame for lineage without re-opening the Dataset.
_DATASET_CACHE: Dict[str, Any] = {}


def generate_dataset(
    session,
    name: str,
    spine_sql: str,
    feature_view_refs: List[Dict[str, str]],
    version: Optional[str] = None,
    spine_timestamp_col: Optional[str] = None,
    spine_label_cols: Optional[List[str]] = None,
    desc: str = "",
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Dict[str, Any]:
    """
    Generate an immutable, versioned Dataset from Feature Views.

    Unlike generate_training_set (which returns a transient DataFrame),
    this creates a Snowflake ML Dataset object that participates in
    ML Lineage: Feature View -> Dataset -> Model.

    The Dataset object is cached so that sfr_log_model can later retrieve
    a Snowpark DataFrame backed by it for sample_input_data.

    Returns:
        Dict with keys: json_path, dataset_name, dataset_version.
    """
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)

    spine_df = session.sql(spine_sql)
    fvs = [
        fs.get_feature_view(ref["name"], ref["version"])
        for ref in feature_view_refs
    ]

    kwargs = {}
    if spine_timestamp_col:
        kwargs["spine_timestamp_col"] = spine_timestamp_col
    if spine_label_cols:
        kwargs["spine_label_cols"] = spine_label_cols
    if desc:
        kwargs["desc"] = desc

    ds = fs.generate_dataset(
        name=name,
        spine_df=spine_df,
        features=fvs,
        version=version,
        **kwargs,
    )

    if ds.selected_version:
        actual_version = str(ds.selected_version.name)
    else:
        actual_version = version or name
    cache_key = f"{name}:{actual_version}"
    _DATASET_CACHE[cache_key] = ds
    print(f"[snowflakeR] Dataset cached: {cache_key} "
          f"(type={type(ds).__name__})")

    # TODO: Add optional Parquet path via ds.read.files() + fsspec
    # for large datasets. See internal/devops/TODO.md.
    pdf = ds.read.to_pandas()
    json_path = _to_json_tempfile(pdf)

    return {
        "json_path": json_path,
        "dataset_name": name,
        "dataset_version": actual_version,
    }


def get_cached_dataset(name: str, version: str):
    """Retrieve a cached Dataset object for use as sample_input_data."""
    cache_key = f"{name}:{version}"
    return _DATASET_CACHE.get(cache_key)


def retrieve_features(
    session,
    spine_sql: str,
    feature_view_refs: List[Dict[str, str]],
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Any:
    """
    Retrieve feature values for inference (no labels, no PIT).

    Args:
        session: Active Snowpark Session.
        spine_sql: SQL for entity key values.
        feature_view_refs: List of dicts with "name" and "version" keys.
        database: Feature Store database.
        schema: Feature Store schema.
        warehouse: Default warehouse.

    Returns:
        pandas DataFrame with feature values.
    """
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)

    spine_df = session.sql(spine_sql)
    fvs = [fs.get_feature_view(ref["name"], ref["version"]) for ref in feature_view_refs]

    result_df = fs.generate_training_set(
        spine_df=spine_df,
        features=fvs,
    )

    return _to_json_tempfile(result_df.to_pandas())


# =============================================================================
# Additional operations
# =============================================================================

def update_entity(
    session,
    name: str,
    desc: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> None:
    """Update an entity's description."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    entity = fs.get_entity(name)
    fs.update_entity(name, desc=desc)


def get_refresh_history(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    verbose: bool = False,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Any:
    """Get refresh history for a Feature View. Returns pandas DataFrame."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    return _pandas_to_r_dict(fs.get_refresh_history(name, version, verbose=verbose).to_pandas())


def setup_feature_store_schema(
    session,
    database: str,
    schema: str,
    warehouse: str,
) -> None:
    """
    Set up the Feature Store schema and required objects.

    Calls the standalone setup_feature_store() helper from snowflake.ml.
    """
    from snowflake.ml.feature_store import setup_feature_store

    setup_feature_store(
        session=session,
        database=database,
        schema=schema,
        warehouse=warehouse,
    )
